
[Structures]

	[Structures.tower]

		[Structures.tower.placement]
			#
			# Percent chance of generating in an allowed chunk.
			# Default: 75
			#Range: 0 ~ 100
			probability = 75

		[Structures.tower.configured_structures]

			[Structures.tower.configured_structures.configured]

				[Structures.tower.configured_structures.configured.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_tower"]
					biomes = ["#dungeons_plus:has_structure/has_tower"]

	[Structures.leviathan]

		[Structures.leviathan.placement]
			#
			# Percent chance of generating in an allowed chunk.
			# Default: 75
			#Range: 0 ~ 100
			probability = 75

		[Structures.leviathan.configured_structures]

			[Structures.leviathan.configured_structures.configured]

				[Structures.leviathan.configured_structures.configured.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_leviathan"]
					biomes = ["#dungeons_plus:has_structure/has_leviathan"]

	[Structures.snowy_temple]

		[Structures.snowy_temple.placement]
			#
			# Percent chance of generating in an allowed chunk.
			# Default: 75
			#Range: 0 ~ 100
			probability = 75

		[Structures.snowy_temple.configured_structures]

			[Structures.snowy_temple.configured_structures.configured]

				[Structures.snowy_temple.configured_structures.configured.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_snowy_temple"]
					biomes = ["#dungeons_plus:has_structure/has_snowy_temple"]

	[Structures.reanimated_ruins]

		[Structures.reanimated_ruins.placement]
			#
			# Percent chance of generating in an allowed chunk.
			# Default: 75
			#Range: 0 ~ 100
			probability = 75

		[Structures.reanimated_ruins.configured_structures]

			[Structures.reanimated_ruins.configured_structures.mossy]

				[Structures.reanimated_ruins.configured_structures.mossy.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_reanimated_ruins_mossy"]
					biomes = ["#dungeons_plus:has_structure/has_reanimated_ruins_mossy"]

			[Structures.reanimated_ruins.configured_structures.mesa]

				[Structures.reanimated_ruins.configured_structures.mesa.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_reanimated_ruins_mesa"]
					biomes = ["#dungeons_plus:has_structure/has_reanimated_ruins_mesa"]

			[Structures.reanimated_ruins.configured_structures.frozen]

				[Structures.reanimated_ruins.configured_structures.frozen.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_reanimated_ruins_frozen"]
					biomes = ["#dungeons_plus:has_structure/has_reanimated_ruins_frozen"]

	[Structures.warped_garden]

		[Structures.warped_garden.placement]
			#
			# Percent chance of generating in an allowed chunk.
			# Default: 75
			#Range: 0 ~ 100
			probability = 75

		[Structures.warped_garden.configured_structures]

			[Structures.warped_garden.configured_structures.configured]

				[Structures.warped_garden.configured_structures.configured.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_warped_garden"]
					biomes = ["#dungeons_plus:has_structure/has_warped_garden"]

	[Structures.soul_prison]

		[Structures.soul_prison.placement]
			#
			# Percent chance of generating in an allowed chunk.
			# Default: 75
			#Range: 0 ~ 100
			probability = 75

		[Structures.soul_prison.configured_structures]

			[Structures.soul_prison.configured_structures.configured]

				[Structures.soul_prison.configured_structures.configured.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_soul_prison"]
					biomes = ["#dungeons_plus:has_structure/has_soul_prison"]

	[Structures.end_ruins]

		[Structures.end_ruins.placement]
			#
			# Percent chance of generating in an allowed chunk.
			# Default: 75
			#Range: 0 ~ 100
			probability = 75

		[Structures.end_ruins.configured_structures]

			[Structures.end_ruins.configured_structures.configured]

				[Structures.end_ruins.configured_structures.configured.biomes]
					#
					# A filter for which biomes this structure should generate in. Entries are formatted as follows:
					# - Biome: "minecraft:plains"
					# - Biome Dictionary Entry: "##structure_gel:birch_forest"
					# - Add ! to the start of an entry to exclude it: "!##structure_gel:frozen_ocean"
					# - Biome Tag: "#minecraft:is_ocean". If using a biome tag, only one can be used and it must be by itself. This does not support "!"
					# Example: ["##structure_gel:wooded", "!minecraft:flower_forest"] This will include all wooded biomes except for flower forests.
					# Default: ["#dungeons_plus:has_structure/has_end_ruins"]
					biomes = ["#dungeons_plus:has_structure/has_end_ruins"]

[Mobs]
	#Percent chance that a Husk will wield a Leviathan Blade in the Leviathan.
	#Range: 0 ~ 100
	husk_leviathan_blade_chance = 5
	#Determines if Husks will drop sand when spawned in the Leviathan.
	husks_drop_sand = true
	#Percent chance that a Stray will wear a Frosted Cowl in the Snowy Temple.
	#Range: 0 ~ 100
	stray_frosted_cowl_chance = 5
	#Determines if Strays will drop ice when spawned in the Snowy Temple.
	strays_drop_ice = true
	#Percent chance that a Drowned will wear a Warped Axe in the Warped Garden.
	#Range: 0 ~ 100
	drowned_warped_axe_chance = 5
	#Percent chance that a Drowned will hold coral in the Warped Garden.
	#Range: 0 ~ 100
	drowned_coral_chance = 30
	#Percent chance that a Skeleton will wield a Soul Cannon in the Soul Prison.
	#Range: 0 ~ 100
	skeleton_soul_cannon_chance = 5

["Mod Compat"]

	["Mod Compat".Waystones]
		#Percent chance for a waystone from Waystones to generate on top of the tower
		#Range: 0 ~ 100
		tower_waystone_chance = 100

