
[general]
	#If true the player mobs will attack all players
	#If false they will ignore players with the same name as themself
	"Attack Twin" = true
	#If the player mobs should be able to open doors.
	"Open Doors" = true
	#The difficulty and above that player mobs can open doors, if enabled above.
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	"Open Doors Difficulty" = "HARD"
	#The chance of the mob getting the ability to pickup items, it's used on mob spawn.
	#Set to -1 to disable.
	#Range: -1.0 ~ 256.0
	"Pickup Item Chance" = 0.55
	#The chance of players dropping a head with their texture.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Player Head Drop Chance" = 1.0
	#The chance of player mobs dropping their head.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Mob Head Drop Chance" = 0.25

#Configs related to spawning the mobs
[spawning]
	#The spawn weight of the mob compared to other mobs.
	#Higher values makes spawning more probable.
	#Default is similar to zombies
	#Range: > 0
	"Spawn Weight" = 100
	#The minimum size of the group of mobs that will spawn.
	#Range: > 1
	"Min Spawn Size" = 4
	#The maximum size of the group of mobs that will spawn.
	#Range: > 1
	"Max Spawn Size" = 4
	#Chance that a player mob will spawn as a baby.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Baby Spawn Chance" = 0.1
	#The id of the dimensions to block spawning in.
	#The player mobs spawn where Zombies spawn, so no need to block dimensions that doesn't contain Zombies.
	#Example id: "minecraft:overworld"
	"Dimension Blocklist" = []
	#Force the mobs to spawn holding items.
	"Force Items Spawn" = false
	#A list of items that the player mobs can spawn with.
	#Default is 40% for a bow, 10% for a crossbow and 50% for a sword, then the swords are distributed after that.
	#There is a separated chance to spawn with an item at all, this is to pick what to spawn when it does
	#Syntax is "namespace:id-weight"
	"Spawn Items" = ["minecraft:bow-90", "minecraft:crossbow-10", "minecraft:stone_sword-64", "minecraft:iron_sword-20", "minecraft:golden_sword-10", "minecraft:diamond_sword-5", "minecraft:netherite_sword-1"]
	#What item to be able to spawn in the offhand
	#Offhand items can only spawn when on hard difficulty
	#It won't spawn an item in the offhand if it spawns with a bow like item.
	#There is a separated chance to spawn with an item at all, this is to pick what it to spawn when it does
	#Syntax is "namespace:id-weight"
	"Spawn Items Offhand" = ["minecraft:shield-1", "minecraft:air-4"]
	#The difficulty and above that player mobs can spawn with items in their offhand.
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	"Offhand Spawn Difficulty" = "HARD"
	#The chance of items spawning in the offhand
	#If holding a projectile weapon this can spawn a tipped arrow if allowed
	#Else it will spawn from the offhand item list
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Offhand Spawn Chance" = 0.5
	#Allow for a change to spawn a random tipped arrow when the mob is holding a projectile weapon
	"Spawn Tipped Arrows" = true
	#A list of potion "namespace:id" to block from getting applied to tipped arrows
	"Tipped Arrow Blocklist" = ["minecraft:awkward", "minecraft:empty", "minecraft:fire_resistance", "minecraft:healing", "minecraft:invisibility", "minecraft:leaping", "minecraft:long_fire_resistance", "minecraft:long_invisibility", "minecraft:long_leaping", "minecraft:long_night_vision", "minecraft:long_regeneration", "minecraft:long_strength", "minecraft:long_swiftness", "minecraft:long_turtle_master", "minecraft:long_water_breathing", "minecraft:luck", "minecraft:mundane", "minecraft:night_vision", "minecraft:regeneration", "minecraft:strength", "minecraft:strong_healing", "minecraft:strong_leaping", "minecraft:strong_regeneration", "minecraft:strong_strength", "minecraft:strong_swiftness", "minecraft:strong_turtle_master", "minecraft:swiftness", "minecraft:thick", "minecraft:turtle_master", "minecraft:water"]

#Configs related to the names of the mobs.
[names]
	#A list of links to get names that the player mobs can have.
	#The names need to be separated by a newline.
	#Names from these links are combined with the named from below
	#As an example you have Twitch subs in the game by using https://whitelist.gorymoon.se
	"Name Links" = []
	#The time interval in minutes when to reload the links (approximately, based on TPS)
	#If set to 0 it will only sync once on load.
	#Range: > 0
	"Reload Interval" = 60
	#A list of names that the player mobs can have.
	"Mob Names" = ["Gory_Moon", "Darkosto", "016Nojr", "BluSunrize", "Buuz135", "Darkere", "Darkhax", "Drullkus", "Ellpeck", "Emberwalker", "Gigabit101", "Kamefrede", "KnightMiner_", "Lat", "LexManos", "Mrbysco", "P3pp3rF1y", "Ray", "Ridanis", "SOTMead", "ShyNieke", "SkySom", "Soaryn", "TamasHenning", "ValkyrieofNight", "XCompWiz", "cpw11", "darkphan", "direwolf20", "dmodoomsirius", "dmodoomsirius", "malte0811", "nekosune", "neptunepink", "vadis365", "wyld", "paulsoaresjr", "Mhykol", "Vswe", "TurkeyDev", "Gen_Deathrow", "Sevadus", "jeb_", "Dinnerbone", "Grumm", "fry_"]
	#If the names in the whitelist should be used for the player mobs.
	"Use Whitelist" = true

